// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_link_ from "./routes/[link].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $analytics_link_ from "./routes/analytics/[link].tsx";
import * as $analytics_index from "./routes/analytics/index.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Alert from "./islands/Alert.tsx";
import * as $CopyButton from "./islands/CopyButton.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[link].tsx": $_link_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/analytics/[link].tsx": $analytics_link_,
    "./routes/analytics/index.tsx": $analytics_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Alert.tsx": $Alert,
    "./islands/CopyButton.tsx": $CopyButton,
    "./islands/Counter.tsx": $Counter,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
